name: 'built-test-deploy'
on:
  pull_request:
    paths-ignore:
      - 'dist/**'
  push:
    branches:
      - main
      - 'releases/*'
    paths-ignore:
      - 'dist/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  test-using-default-dir:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: ./
        with:
          full_text: |
            PROD=0
            TEST=1
      - run: cat .env
      - run: grep -zP "^PROD=0\nTEST=1$" .env
  test-using-provided-dir:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: mkdir __tests__/artifacts
      - uses: ./
        with:
          directory: __tests__/artifacts
          full_text: |
            PROD=0
            TEST=1
      - run: cat __tests__/artifacts/.env
      - run: grep -zP "^PROD=0\nTEST=1$" __tests__/artifacts/.env
  test-override-existing:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: echo 'PROD=0' > .env
      - uses: ./
        with:
          full_text: TEST=1
      - run: cat .env
      - run: grep -zP "^TEST=1$" .env
  test-including-env-vars:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: ./
        with:
          full_text: PROD=0
          include_env_vars: true
        env:
          ACTION_CREATE_ENV_TEST: 1
      - run: cat .env
      - run: grep -zP "^PROD=0\nTEST=1$" .env
  deploy:
    runs-on: ubuntu-latest
    needs:
      - test-using-default-dir
      - test-using-provided-dir
      - test-override-existing
      - test-including-env-vars
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: EndBug/add-and-commit@v7
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'dist'

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default:
          default_author: github_actor

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Auto-deploy commit (WF: build-test-deploy)'

          # The flag used on the pull strategy. Use NO-PULL to avoid the action pulling at all.
          # Default: '--no-rebase'
          pull_strategy: 'NO-PULL'
