name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  test-using-default-dir:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: ./
        with:
          full_text: |
            PROD=0
            TEST=1
      - run: cat .env
      - run: grep -zP "^PROD=0\nTEST=1$" .env
  test-using-provided-dir:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: mkdir __tests__/artifacts
      - uses: ./
        with:
          directory: __tests__/artifacts
          full_text: |
            PROD=0
            TEST=1
      - run: cat __tests__/artifacts/.env
      - run: grep -zP "^PROD=0\nTEST=1$" __tests__/artifacts/.env
  test-override-existing:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: echo 'PROD=0' > .env
      - uses: ./
        with:
          full_text: TEST=1
      - run: cat .env
      - run: grep -zP "^TEST=1$" .env
